### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by amosowerner** [Jschii/fitbit-hr-to-gpx#1]
Quick question, i keep getting a syntax error in the json... not sure what I'm missing.

``➜  fitbit-hr-to-gpx git:(master) ✗ node hr2gpx.js /Users/amoswerner/Downloads/Morning_Ride.gpx /Users/amoswerner/Desktop/hr.json  
undefined:1
<?xml version="1.0" encoding="UTF-8"?>
^

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at doIt (/Users/amoswerner/fitbit-hr-to-gpx/hr2gpx.js:44:23)
    at /Users/amoswerner/fitbit-hr-to-gpx/hr2gpx.js:17:26
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:436:12)
➜  fitbit-hr-to-gpx git:(master) ✗ 

Files attached I'm looking to combine.

Thanks

[gpx-hr_amos.zip](https://github.com/Jschii/fitbit-hr-to-gpx/files/287800/gpx-hr_amos.zip)

**Comment by amosowerner** [comment]
bah... had my paths backwards. awesome tool!
